; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.0.0 on Wed Sep 04 2019 19:48:34 GMT+0100 (BST)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


